using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DeusaldLocalizerCommon;
using JetBrains.Annotations;

namespace DeusaldStoryCommon
{
    /// <summary>
    /// Resolves a logic node's inner content graph into plain rendered data — the title, optional subtitle, an
    /// optional icon (base64 PNG), the ordered text blocks produced by walking the flow spine, and the continuations
    /// it offers. Host-agnostic so the App preview, the Gamebook preview and (later) PDF export share one resolution;
    /// HTML sanitization is left to the caller (see <see cref="PreviewHtmlSanitizer"/>).
    /// </summary>
    [PublicAPI]
    public static class StoryLogicRenderer
    {
        private static readonly Dictionary<Guid, string> _EmptyValues = new();

        /// <summary>A logic node resolved to display text/icon for one combination of variable values.</summary>
        public sealed class RenderedLogic
        {
            public string  Title    { get; set; } = "";
            public string  Subtitle { get; set; } = "";
            public string? IconData { get; set; }

            /// <summary>Every text block in flow order (all App pages concatenated). The Gamebook renders this as one continuous section.</summary>
            public List<RenderedBlock> Blocks { get; set; } = new();

            /// <summary>The App-only paging of the content — one entry per "Click here to continue…" screen (see <see cref="RenderedPage"/>). Empty for the Gamebook.</summary>
            public List<RenderedPage> Pages { get; set; } = new();

            /// <summary>The continuations this node offers (authored choices, or the enumerated choice definitions in Single-path).</summary>
            public List<RenderedChoice> Choices { get; set; } = new();

            /// <summary>
            /// The choices referenced inline from the node's text with a <c>&lt;choice=Name&gt;</c> tag, resolved by name.
            /// When non-empty the standalone choice buttons / continue lines are suppressed — the inline links carry the
            /// navigation instead. The label <see cref="RenderedInlineChoice.Text"/> is medium-appropriate.
            /// </summary>
            public List<RenderedInlineChoice> InlineChoices { get; set; } = new();

            /// <summary>
            /// App-only, Hub Paths mode — one entry per visible choice, carrying the inline-rendered destination node so
            /// the preview draws it as a sub-card. Empty in every other mode / medium.
            /// </summary>
            public List<RenderedSubHub> SubHubs { get; set; } = new();

            /// <summary>Player-facing storage instructions generated by this node's Set operations, in flow order.</summary>
            public List<StorageInstruction> Instructions { get; set; } = new();

            /// <summary>SmartFormat render failures encountered while resolving this node's text.</summary>
            public List<string> Errors { get; set; } = new();
        }

        /// <summary>
        /// One App "page" — the content shown on a single screen, ending in a "Click here to continue…" button (or the
        /// exit choices on the last page). A Split-for-App node on the flow spine starts a new page; input fields land on
        /// the page whose flow segment contains them, positioned above or below that page's text by their own placement.
        /// </summary>
        public sealed class RenderedPage
        {
            public List<StorageInstruction> Above  { get; set; } = new();
            public List<RenderedBlock>      Blocks { get; set; } = new();
            public List<StorageInstruction> Below  { get; set; } = new();
        }

        /// <summary>One rendered text block — the resolved (sanitizable) text plus the frame style it is drawn in.</summary>
        public sealed class RenderedBlock
        {
            public RenderedBlock() { }
            public RenderedBlock(string text, StoryTextFrameStyle frameStyle)
            {
                Text       = text;
                FrameStyle = frameStyle;
            }
            public string              Text       { get; set; } = "";
            public StoryTextFrameStyle FrameStyle { get; set; } = StoryTextFrameStyle.Normal;
        }

        /// <summary>One resolved continuation — its player-facing text plus how the App/Gamebook continues from it.</summary>
        public sealed class RenderedChoice
        {
            public string Text { get; set; } = "";

            /// <summary>The <see cref="StoryChoice.Id"/> this was rendered from (empty for an enumerated Single-path continuation).</summary>
            public Guid ChoiceId { get; set; }

            /// <summary>The outer connection point the story continues from — the choice's own output (ManyPaths) or the node's shared <see cref="StoryLogicNode.SingleOut"/>. Empty when unwired.</summary>
            public Guid OuterFlowOut { get; set; }

            /// <summary>
            /// Single-path only — the variable values this continuation pins (its Choice variables, plus any real
            /// variable an entry fixes). The App navigator carries these into the next node; the Gamebook uses them to
            /// pick which downstream section to jump to.
            /// </summary>
            public Dictionary<Guid, string> Pins { get; set; } = new();
        }

        /// <summary>
        /// One Hub Paths sub-card — a visible choice whose destination logic node is rendered inline. <see cref="Link"/>
        /// is the choice used to navigate into it; <see cref="Content"/> is the destination's rendered content (null when
        /// the destination is the story End, dangling or unwired — see <see cref="Status"/>).
        /// </summary>
        public sealed class RenderedSubHub
        {
            public RenderedChoice              Link    { get; set; } = new();
            public RenderedLogic?              Content { get; set; }
            public StoryFlowNavigator.NextKind Status  { get; set; } = StoryFlowNavigator.NextKind.Dangling;

            /// <summary>The destination logic node's id (Empty for End/dangling/unwired). Used to spot a hub pointing at itself.</summary>
            public Guid TargetLogicId { get; set; }

            /// <summary>The route just loops back to the hub (directly or through the destination's own exit), so the "click here" button is hidden.</summary>
            public bool LoopsToHub { get; set; }
        }

        /// <summary>One choice referenced inline from the node's text via a <c>&lt;choice=Name&gt;</c> tag.</summary>
        public sealed class RenderedInlineChoice
        {
            /// <summary>The name written in the tag — how a text occurrence maps back to this entry (case-insensitive). Empty for a bare <c>&lt;choice&gt;</c> (the node's automatic continue).</summary>
            public string Name { get; set; } = "";

            /// <summary>The <see cref="StoryChoice.Id"/> this resolved to.</summary>
            public Guid ChoiceId { get; set; }

            /// <summary>The choice's own label, resolved for the medium; empty ⇒ the default "Click here…".</summary>
            public string Text { get; set; } = "";

            /// <summary>The outer connection point the story continues from — as <see cref="RenderedChoice.OuterFlowOut"/>. Empty when unwired.</summary>
            public Guid OuterFlowOut { get; set; }
        }

        /// <summary>
        /// Matches an inline choice reference in raw (pre-sanitized) node text: named <c>&lt;choice=Name&gt;</c> (group 1 is the
        /// name) or bare <c>&lt;choice&gt;</c> (the node's automatic continue). The empty second alternative <c>()</c> keeps a
        /// capture participating for the bare form so <see cref="Regex.Split(string)"/> emits exactly one token per match — a
        /// non-participating group is dropped by Split, which would break the even-text / odd-tag indexing in the App renderer.
        /// </summary>
        public static readonly Regex InlineChoiceTag = new Regex(@"<choice(?:=([^>]+?)|())>", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        /// <summary>
        /// Resolves <paramref name="logic"/> against <paramref name="values"/> (variable id → value). <paramref name="paper"/>
        /// selects the light icon slot and the light theme; <paramref name="target"/> selects App vs Gamebook resolution.
        /// <paramref name="pinned"/> carries the variable values the incoming choice fixed for this render (one Gamebook
        /// section, or one App navigation), which print concretely instead of as slot pills.
        /// </summary>
        public static RenderedLogic Render(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, bool paper, StoryRenderTarget target = StoryRenderTarget.App,
            bool renderSubHubs = true, IReadOnlyDictionary<Guid, string>? pinned = null)
        {
            // Seed the built-in Theme value from the render's theme flag so every sub-resolver reads it like an
            // ordinary pinned value — Light in the always-light Gamebook, else the App preview's toggle.
            values = new Dictionary<Guid, string>(values)
            {
                [StoryBuiltInVariables.ThemeId] = paper ? StoryBuiltInVariables.LightValue : StoryBuiltInVariables.DarkValue
            };

            List<string> errors = new();

            // One dictionary for the whole render. The spine walk mutates it as Constant Variable / Set / Randomized
            // Instruction nodes execute, so anything resolved AFTER the walk sees what the graph computed.
            StoryVariableDictionary.Context ctx = StoryVariableDictionary.Build(project, logic, values, target, pinned);

            // The App pages the content into "Click here to continue…" screens at each Split-for-App node; the Gamebook
            // ignores splits and reads as one continuous block. Blocks (flat) stays populated for both mediums.
            List<RenderedPage>  pages;
            List<RenderedBlock> blocks;
            if (target == StoryRenderTarget.App)
            {
                pages  = BuildAppPages(project, localization, logic, ctx, errors);
                blocks = pages.SelectMany(p => p.Blocks).ToList();
            }
            else
            {
                blocks = WalkTextBlocks(project, localization, logic, ctx, errors);
                pages  = new();
            }

            // Resolved AFTER the spine so a Constant Variable node's value is visible to the header and the choices.
            List<RenderedChoice>       choices       = ResolveChoices(project, localization, logic, ctx, errors);
            List<RenderedInlineChoice> inlineChoices = ResolveInlineChoices(localization, logic, ctx, blocks, choices, target, errors);

            // Hub Paths (App only) — render each visible choice's destination inline as a sub-card. renderSubHubs is
            // passed false into the nested render so a hub pointing at another hub cannot recurse past one level.
            List<RenderedSubHub> subHubs = target == StoryRenderTarget.App && logic.ExitMode == StoryLogicExitMode.HubPaths && renderSubHubs
                ? BuildSubHubs(project, localization, logic, choices, paper)
                : new();

            return new RenderedLogic
            {
                Title         = ResolveText(localization, logic.EntryTitle, ctx, errors),
                Subtitle      = ResolveText(localization, logic.EntrySubtitle, ctx, errors),
                IconData      = ResolveEntryIcon(project, logic, paper),
                Blocks        = blocks,
                Pages         = pages,
                Choices       = choices,
                InlineChoices = inlineChoices,
                SubHubs       = subHubs,
                Instructions  = StoryStorageInstructions.For(project, localization, logic, ctx),
                Errors        = errors
            };
        }

        /// <summary>
        /// Collects the choices referenced by a <c>&lt;choice=Name&gt;</c> tag anywhere in the node's text blocks,
        /// resolving each name (case-insensitive) to one of <paramref name="logic"/>'s choices. A name that matches no
        /// choice is skipped (its tag is left visible). A bare <c>&lt;choice&gt;</c> (no name) is the node's automatic
        /// "continue" link — App only, resolved against the already-computed <paramref name="choices"/>.
        /// </summary>
        private static List<RenderedInlineChoice> ResolveInlineChoices(
            LocProject? localization, StoryLogicNode logic, StoryVariableDictionary.Context ctx,
            List<RenderedBlock> blocks, List<RenderedChoice> choices, StoryRenderTarget target, List<string> errors)
        {
            List<RenderedInlineChoice> result = new();
            HashSet<string>            seen   = new(StringComparer.OrdinalIgnoreCase);
            foreach (RenderedBlock block in blocks)
                foreach (Match m in InlineChoiceTag.Matches(block.Text))
                {
                    string name = m.Groups[1].Value.Trim();
                    if (!seen.Add(name)) continue;

                    if (name.Length == 0)
                    {
                        // Bare <choice>: the automatic continue. App only, and only when the node's exit is unambiguous;
                        // otherwise leave the tag literal (a non-App medium or a many-choice node with no auto-resolution).
                        if (target != StoryRenderTarget.App) continue;
                        if (!TryBareContinueTarget(logic, choices, out Guid bareOut, out Guid bareChoiceId)) continue;
                        result.Add(new RenderedInlineChoice { Name = "", ChoiceId = bareChoiceId, Text = "", OuterFlowOut = bareOut });
                        continue;
                    }
                    if (logic.Choices.Find(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase)) is not StoryChoice choice) continue;
                    result.Add(new RenderedInlineChoice
                    {
                        Name         = name,
                        ChoiceId     = choice.Id,
                        Text         = ResolveText(localization, choice.Label, ctx, errors),
                        OuterFlowOut = OuterFlowOut(logic, choice)
                    });
                }
            return result;
        }

        /// <summary>
        /// The exit a bare inline <c>&lt;choice&gt;</c> continues from (and the choice id, when known): the App
        /// auto-resolved pick, the single shared Single-path exit, or a lone authored choice. Ambiguous — many choices
        /// with no auto-resolution — yields no target, so the tag stays literal.
        /// </summary>
        private static bool TryBareContinueTarget(StoryLogicNode logic, List<RenderedChoice> choices, out Guid outerFlowOut, out Guid choiceId)
        {
            outerFlowOut = Guid.Empty;
            choiceId     = Guid.Empty;

            // App auto-resolution already collapsed the exits to a single pick — follow exactly that (it knows the id).
            (bool autoResolve, StoryExitAutoMode mode) = ExitResolution(logic, StoryRenderTarget.App);
            if (autoResolve && mode == StoryExitAutoMode.AutomaticChoice && choices.Count == 1)
            {
                outerFlowOut = choices[0].OuterFlowOut;
                choiceId     = choices[0].ChoiceId;
                return true;
            }
            // Single-path — one shared exit whichever continuation rides it.
            if (logic.ExitMode == StoryLogicExitMode.SinglePath)
            {
                outerFlowOut = logic.SingleOut.Id;
                return true;
            }
            // Many-paths with a single authored choice — unambiguous.
            if (logic.ExitMode == StoryLogicExitMode.ManyPaths && logic.Choices.Count == 1)
            {
                outerFlowOut = OuterFlowOut(logic, logic.Choices[0]);
                choiceId     = logic.Choices[0].Id;
                return true;
            }
            return false;
        }

        /// <summary>
        /// Builds a Hub Paths sub-card per already-visible choice: resolves where the choice leads and, when it reaches
        /// another logic node, renders that node's content inline (with its own sub-hubs suppressed, bounding recursion).
        /// A fresh navigation seeds no live variables, so sub-card content is resolved against an empty value set.
        /// </summary>
        private static List<RenderedSubHub> BuildSubHubs(StoryProject project, LocProject? localization, StoryLogicNode hub, List<RenderedChoice> choices, bool paper)
        {
            List<RenderedSubHub> result = new();
            foreach (RenderedChoice choice in choices)
            {
                if (choice.OuterFlowOut == Guid.Empty)
                {
                    result.Add(new RenderedSubHub { Link = choice, Content = null, Status = StoryFlowNavigator.NextKind.Dangling });
                    continue;
                }
                StoryFlowNavigator.NextLogicResult next = StoryFlowNavigator.ResolveNextLogic(project, choice.OuterFlowOut);
                result.Add(new RenderedSubHub
                {
                    Link          = choice,
                    Status        = next.Kind,
                    TargetLogicId = next.Logic?.Id ?? Guid.Empty,
                    LoopsToHub    = next.Kind == StoryFlowNavigator.NextKind.Logic && next.Logic is not null && DestinationLoopsBack(project, hub, next.Logic),
                    Content = next.Kind == StoryFlowNavigator.NextKind.Logic && next.Logic is not null
                        ? Render(project, localization, next.Logic, _EmptyValues, paper, StoryRenderTarget.App, renderSubHubs: false)
                        : null
                });
            }
            return result;
        }

        /// <summary>
        /// Whether a sub-card's destination just loops back to the hub — either it <b>is</b> the hub, or following any of
        /// its own exits reaches the hub. The whole destination node is already shown inline, so such a route offers the
        /// player nothing new and its "click here" button is hidden.
        /// </summary>
        private static bool DestinationLoopsBack(StoryProject project, StoryLogicNode hub, StoryLogicNode dest)
        {
            if (dest.Id == hub.Id) return true;

            IEnumerable<Guid> exits = dest.ExitMode == StoryLogicExitMode.SinglePath
                ? new[] { dest.SingleOut.Id }
                : dest.Choices.Select(c => c.OuterFlowOut.Id);
            foreach (Guid exit in exits)
            {
                StoryFlowNavigator.NextLogicResult next = StoryFlowNavigator.ResolveNextLogic(project, exit);
                if (next.Kind == StoryFlowNavigator.NextKind.Logic && next.Logic?.Id == hub.Id) return true;
            }
            return false;
        }

        /// <summary>The continuations this node offers for <paramref name="target"/>.</summary>
        public static List<RenderedChoice> Choices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target = StoryRenderTarget.App)
        {
            StoryVariableDictionary.Context ctx = StoryVariableDictionary.Build(project, logic, values, target);
            return ResolveChoices(project, localization, logic, ctx, new List<string>());
        }

        // ── Flow spine walk ──────────────────────────────────────────────────────

        /// <summary>
        /// Walks the flow spine from the Entry, invoking <paramref name="visit"/> for each node in flow order. Every
        /// inner node is one-in / one-out, so the walk is linear; a Condition node is the only branch — it detours into
        /// its "condition true" block (up to the paired End node) when the condition holds, then continues from its
        /// "continue" output. Recursion handles nesting; a shared visited set stops cycles.
        /// <para>
        /// The single traversal both preview builders and the storage-instruction ordering share, so flow order can
        /// never disagree between them.
        /// </para>
        /// </summary>
        public static void WalkSpine(StoryProject project, StoryLogicNode logic, StoryVariableDictionary.Context ctx, Action<object> visit)
        {
            HashSet<Guid> visited = new();

            void Walk(Guid target)
            {
                for (int guard = 0; guard < 256; ++guard)
                {
                    if (target == Guid.Empty || !visited.Add(target)) break;

                    if (logic.TextNodes.Find(n => n.FlowIn.Id == target) is StoryTextNode text)
                    {
                        visit(text);
                        target = FlowTargetOf(logic, text.FlowOut.Id);
                    }
                    else if (logic.SplitForAppNodes.Find(n => n.FlowIn.Id == target) is StorySplitForAppNode split)
                    {
                        visit(split);
                        target = FlowTargetOf(logic, split.FlowOut.Id);
                    }
                    else if (logic.SetVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetVariableNode set)
                    {
                        visit(set);
                        target = FlowTargetOf(logic, set.FlowOut.Id);
                    }
                    else if (logic.ConstantVariableNodes.Find(n => n.FlowIn.Id == target) is StoryConstantVariableNode constant)
                    {
                        visit(constant);
                        target = FlowTargetOf(logic, constant.FlowOut.Id);
                    }
                    else if (logic.RandomizedInstructionNodes.Find(n => n.FlowIn.Id == target) is StoryRandomizedInstructionNode random)
                    {
                        visit(random);
                        target = FlowTargetOf(logic, random.FlowOut.Id);
                    }
                    else if (logic.ConditionFlowNodes.Find(n => n.FlowIn.Id == target) is StoryConditionFlowNode cf)
                    {
                        if (StoryLogicFlow.EvaluateConditionFlow(cf, ctx))
                            Walk(FlowTargetOf(logic, cf.ConditionTrueOut.Id));
                        target = FlowTargetOf(logic, cf.ContinueOut.Id);
                    }
                    else
                        break; // reached the Exit node's flow input, an End-condition node, or a leaf
                }
            }

            Walk(FlowTargetOf(logic, logic.EntryPoint.Id));
        }

        /// <summary>
        /// Publishes a spine node's contribution to the variable dictionary. Called for every node the walk visits, by
        /// every caller, so the dictionary evolves identically no matter who is walking.
        /// </summary>
        private static void ApplyToContext(StoryProject project, StoryLogicNode logic, LocProject? localization, object node, StoryVariableDictionary.Context ctx, List<string> errors)
        {
            switch (node)
            {
                case StoryConstantVariableNode constant when !string.IsNullOrWhiteSpace(constant.Name):
                    ctx.Set(Guid.Empty, constant.Name, constant.Value);
                    break;

                case StoryRandomizedInstructionNode random:
                {
                    string token = RandomTokenName(random);
                    if (ctx.Target == StoryRenderTarget.App)
                    {
                        string drawn = !string.IsNullOrEmpty(random.PreviewValue)
                            ? random.PreviewValue
                            : RandomActiveRange(project, random, ctx).FirstOrDefault() ?? "";
                        ctx.Set(random.SaveToVariable ? random.TargetVariableId : Guid.Empty, token, drawn);
                    }
                    else ctx.HasOmittedVariable = true; // the player physically rolls — unknowable on paper
                    break;
                }

                case StorySetVariableNode set when set.SelectedVariableId != Guid.Empty:
                {
                    // Only a value the printed book can also know is worth publishing; anything live stays as it was.
                    if (ctx.Target != StoryRenderTarget.App) break;
                    if (StoryVariableCatalog.Resolve(project, set.SelectedVariableId) is not StoryVariable target) break;
                    string? assigned = SetAssignedValue(project, set, ctx);
                    if (assigned is not null) ctx.Set(target.Id, target.Name, assigned);
                    break;
                }
            }
        }

        /// <summary>The value a Set node assigns when it is statically knowable, else null (a random draw or a player entry).</summary>
        private static string? SetAssignedValue(StoryProject project, StorySetVariableNode set, StoryVariableDictionary.Context ctx)
        {
            if (StoryVariableCatalog.Resolve(project, set.SelectedVariableId) is not StoryVariable target) return null;

            if (target.Scope == StoryVariableScope.External)
                return set.ExternalMode switch
                {
                    StorySetExternalVariableMode.SpecificValue => set.ExternalValue,
                    _ => set.ValueVariableId != Guid.Empty && ctx.ById.TryGetValue(set.ValueVariableId, out string? wired)
                        ? Remap(set, wired)
                        : null
                };

            if (target.InternalSubtype == StoryInternalSubtype.Text)
                return set.StringMode == StringValueMode.Specific ? set.StringValue : null;

            return set.Assignment == NumberAssignment.SetSpecific
                ? set.SpecificValue.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : null;
        }

        /// <summary>Applies a Set node's remap table to an incoming value (identity when the node isn't remapping).</summary>
        private static string Remap(StorySetVariableNode set, string incoming) =>
            set.ExternalMode == StorySetExternalVariableMode.RemapFromVariable
                ? set.ValueMap.Find(m => string.Equals(m.From, incoming, StringComparison.OrdinalIgnoreCase))?.To ?? incoming
                : incoming;

        /// <summary>
        /// Walks the spine collecting the ordered text blocks (the Gamebook path). A block switched off for the
        /// Gamebook is skipped; Split-for-App nodes have no effect here — the book reads as one continuous section.
        /// </summary>
        private static List<RenderedBlock> WalkTextBlocks(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            List<RenderedBlock> blocks = new();

            WalkSpine(project, logic, ctx, node =>
            {
                ApplyToContext(project, logic, localization, node, ctx, errors);
                switch (node)
                {
                    case StoryTextNode text when text.RenderInGamebook:
                        blocks.Add(new RenderedBlock(ResolveText(localization, text.Text, ctx, errors), text.FrameStyle));
                        break;
                    case StoryRandomizedInstructionNode random:
                        blocks.Add(new RenderedBlock(RenderRandomized(project, localization, random, ctx, errors), StoryTextFrameStyle.Normal));
                        break;
                }
            });

            return blocks;
        }

        /// <summary>
        /// Builds the App's "Click here to continue…" pages by walking the spine once: text blocks and the input fields
        /// produced by Set nodes are collected in flow order onto the current page, a Split-for-App node starts a new
        /// page, and each input lands above or below its page's text by its own placement. Set nodes left off the chain
        /// still surface their input on the last page. Fully empty pages are dropped; at least one is always returned.
        /// </summary>
        private static List<RenderedPage> BuildAppPages(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            List<RenderedPage> pages   = new() { new() };
            HashSet<Guid>      emitted = new(); // Set nodes already surfaced on the spine

            void AddInput(RenderedPage page, StorageInstruction? entry)
            {
                if (entry is not { IsAppInput: true }) return; // the App surfaces only player-input fields
                (entry.Placement == StorageInstructionPlacement.Above ? page.Above : page.Below).Add(entry);
            }

            WalkSpine(project, logic, ctx, node =>
            {
                ApplyToContext(project, logic, localization, node, ctx, errors);
                RenderedPage page = pages[^1];
                switch (node)
                {
                    case StoryTextNode text when text.RenderInApp:
                        page.Blocks.Add(new RenderedBlock(ResolveText(localization, text.Text, ctx, errors), text.FrameStyle));
                        break;
                    case StorySplitForAppNode:
                        pages.Add(new());
                        break;
                    case StorySetVariableNode set:
                        AddInput(page, StoryStorageInstructions.ForSet(project, localization, logic, set, ctx));
                        emitted.Add(set.Id);
                        break;
                    case StoryRandomizedInstructionNode random:
                        page.Blocks.Add(new RenderedBlock(RenderRandomized(project, localization, random, ctx, errors), StoryTextFrameStyle.Normal));
                        break;
                }
            });

            // Set nodes dropped in but left unwired still run when the story visits the node — surface their input on
            // the last page (they have no flow position of their own).
            RenderedPage last = pages[^1];
            bool Wired(StoryConnectionPoint flowIn, StoryConnectionPoint flowOut) =>
                logic.ContentConnections.Exists(c => c.ToPoint == flowIn.Id || c.FromPoint == flowOut.Id);
            foreach (StorySetVariableNode set in logic.SetVariableNodes)
                if (!emitted.Contains(set.Id) && !Wired(set.FlowIn, set.FlowOut))
                    AddInput(last, StoryStorageInstructions.ForSet(project, localization, logic, set, ctx));

            pages.RemoveAll(p => p.Above.Count == 0 && p.Blocks.Count == 0 && p.Below.Count == 0);
            if (pages.Count == 0) pages.Add(new());
            return pages;
        }

        // ── Choices ──────────────────────────────────────────────────────────────

        /// <summary>Resolves this node's continuations for the medium.</summary>
        private static List<RenderedChoice> ResolveChoices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            // Single-path: the continuations ARE the enumeration of the choice definitions, all riding SingleOut.
            if (logic.ExitMode == StoryLogicExitMode.SinglePath)
                return ResolveDefinitionChoices(project, localization, logic, ctx, errors);

            List<RenderedChoice> result = new();
            if (logic.Choices.Count == 0) return result;

            // Automatic Choice is App-only; Choice Visibility resolves in both mediums. Hub Paths always uses Choice
            // Visibility; otherwise the node's own ExitAutoMode decides.
            (bool autoResolve, StoryExitAutoMode mode) = ExitResolution(logic, ctx.Target);

            if (autoResolve && mode == StoryExitAutoMode.AutomaticChoice)
            {
                StoryChoice? picked = logic.Choices.FirstOrDefault(c => c.IsElse || (c.Condition?.Evaluate(id => Operand(ctx, id)) ?? false));
                if (picked is not null)
                    result.Add(new RenderedChoice
                    {
                        Text         = ResolveText(localization, logic.AutoText, ctx, errors),
                        ChoiceId     = picked.Id,
                        OuterFlowOut = OuterFlowOut(logic, picked)
                    });
                return result;
            }

            foreach (StoryChoice choice in logic.Choices)
            {
                // Choice Visibility — show each choice only when its condition is empty (always) or true. An empty
                // Group evaluates true, so the "empty ⇒ always shown" rule collapses to `?? true`.
                if (autoResolve && mode == StoryExitAutoMode.ChoiceVisibility
                    && !(choice.Condition?.Evaluate(id => Operand(ctx, id)) ?? true)) continue;

                result.Add(new RenderedChoice
                {
                    Text         = ResolveText(localization, choice.Label, ctx, errors),
                    ChoiceId     = choice.Id,
                    OuterFlowOut = OuterFlowOut(logic, choice)
                });
            }
            return result;
        }

        /// <summary>
        /// Single-path — one continuation per combination of the node's choice definitions. Each is labelled by the key
        /// its entry resolved to (the variable's value key, the range band's own key, or the option's), rendered with
        /// the combination's own pins bound so the label can print the value it stands for.
        /// </summary>
        private static List<RenderedChoice> ResolveDefinitionChoices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            List<RenderedChoice> result = new();
            if (logic.ChoiceDefinitions.Count == 0) return result;

            foreach (StoryChoiceSources.Combination combo in
                     StoryChoiceSources.Combinations(project, logic, StoryGamebookPreview.MAX_SECTIONS, out _))
            {
                if (combo.Entries.Count == 0) continue;

                // The last definition's entry carries the label; earlier ones only narrow the combination.
                StoryChoiceSources.ChoiceEntry label = combo.Entries[^1];
                result.Add(new RenderedChoice
                {
                    Text         = ResolveChoiceLabel(localization, label, combo, ctx, errors),
                    ChoiceId     = Guid.Empty,
                    OuterFlowOut = logic.SingleOut.Id,
                    Pins         = new Dictionary<Guid, string>(combo.Pins)
                });
            }
            return result;
        }

        /// <summary>
        /// One enumerated continuation's label: its localization key SmartFormatted with the combination's pins bound
        /// (so <c>{Health}</c> prints the value this button stands for) plus <c>{Range}</c> for a band. Falls back to
        /// the entry's literal text when it carries no key.
        /// </summary>
        private static string ResolveChoiceLabel(
            LocProject? localization, StoryChoiceSources.ChoiceEntry entry, StoryChoiceSources.Combination combo,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            if (entry.KeyId == Guid.Empty) return entry.FallbackText;

            Dictionary<string, object> tokens = new(ctx.Tokens, StringComparer.OrdinalIgnoreCase);
            foreach (KeyValuePair<Guid, string> pin in combo.Pins)
                if (ctx.Project.Variables.TryGetValue(pin.Key, out StoryVariable? v)) tokens[v.Name] = pin.Value;
                else if (StoryChoiceVariables.Find(pin.Key) is StoryVariable cv) tokens[cv.Name] = pin.Value;
            if (entry.RangeToken is not null) tokens["Range"] = entry.RangeToken;

            string rendered = StoryConditionPreview.Render(LocalizedText(localization, entry.KeyId), tokens, out string? error);
            if (error is not null) AddSmartFormatError(errors, ctx, error);
            return rendered;
        }

        /// <summary>
        /// Whether choice auto-resolution is active for this medium, and the effective mode — Hub Paths always resolves
        /// as Choice Visibility, otherwise the node's own <see cref="StoryLogicNode.ExitAutoMode"/>.
        /// </summary>
        private static (bool autoResolve, StoryExitAutoMode mode) ExitResolution(StoryLogicNode logic, StoryRenderTarget target)
        {
            StoryExitAutoMode mode = logic.ExitMode == StoryLogicExitMode.HubPaths ? StoryExitAutoMode.ChoiceVisibility : logic.ExitAutoMode;
            // Choice Visibility resolves in BOTH mediums: the Gamebook pins the incoming choice values per section, so
            // each printed section can hide the options its variables rule out. Automatic Choice collapses to a single
            // live pick, so it stays App-only.
            bool mediumOk = target == StoryRenderTarget.App || mode == StoryExitAutoMode.ChoiceVisibility;
            return (mediumOk && logic.ExitAutoResolve, mode);
        }

        /// <summary>A condition operand's value — a variable id looked up in the render's dictionary.</summary>
        private static string Operand(StoryVariableDictionary.Context ctx, Guid variableId) =>
            ctx.ById.TryGetValue(variableId, out string? value) ? value : "";

        /// <summary>The outer connection point a choice continues from.</summary>
        private static Guid OuterFlowOut(StoryLogicNode logic, StoryChoice choice) =>
            logic.ExitMode == StoryLogicExitMode.SinglePath ? logic.SingleOut.Id : choice.OuterFlowOut.Id;

        private static Guid FlowTargetOf(StoryLogicNode logic, Guid fromPoint) =>
            logic.ContentConnections.Find(c => c.FromPoint == fromPoint)?.ToPoint ?? Guid.Empty;

        // ── Text resolution ──────────────────────────────────────────────────────

        /// <summary>
        /// Resolves one authored text: its localization key's main-language template, SmartFormatted against the
        /// render's variable dictionary, case-transformed, then wrapped in its literal prefix/suffix.
        /// </summary>
        public static string ResolveText(
            LocProject? localization, StoryTextConfig config, StoryVariableDictionary.Context ctx, List<string> errors,
            IReadOnlyDictionary<string, object>? extraTokens = null)
        {
            if (config.IsEmpty) return "";

            IDictionary<string, object> tokens = ctx.Tokens;
            if (extraTokens is not null)
            {
                Dictionary<string, object> merged = new(ctx.Tokens, StringComparer.OrdinalIgnoreCase);
                foreach (KeyValuePair<string, object> kv in extraTokens) merged[kv.Key] = kv.Value;
                tokens = merged;
            }

            string rendered = StoryConditionPreview.Render(LocalizedText(localization, config.KeyId), tokens, out string? error);
            if (error is not null) AddSmartFormatError(errors, ctx, error);

            return config.Prefix + ApplyCasing(rendered, config.Casing) + config.Suffix;
        }

        /// <summary>Records a SmartFormat failure, pointing at the Gamebook-omitted-value cause when that is the likely reason.</summary>
        private static void AddSmartFormatError(List<string> errors, StoryVariableDictionary.Context ctx, string error) =>
            errors.Add(ctx.HasOmittedVariable
                ? UiLang.T(Localization.Services.Renderer.smartFormatFailedGamebook, new Dictionary<string, object> { ["error"] = error })
                : UiLang.T(Localization.Services.Renderer.smartFormatFailed,         new Dictionary<string, object> { ["error"] = error }));

        // ── Randomized instruction ───────────────────────────────────────────────

        /// <summary>The SmartFormat token a Randomized Instruction node's result fills.</summary>
        private static string RandomTokenName(StoryRandomizedInstructionNode ri) =>
            string.IsNullOrWhiteSpace(ri.ResultToken) ? "RandomResult" : ri.ResultToken.Trim();

        /// <summary>
        /// Renders a Randomized Instruction node's own block: the App shows the single drawn value, the Gamebook prints
        /// the whole D12 roll-to-outcome table. Both bind <c>{ResultToken}</c> and <c>{RandomInstruction}</c>.
        /// </summary>
        private static string RenderRandomized(
            StoryProject project, LocProject? localization, StoryRandomizedInstructionNode ri,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            List<string> range = RandomActiveRange(project, ri, ctx);
            string       token = RandomTokenName(ri);

            Dictionary<string, object> extra = new(StringComparer.OrdinalIgnoreCase);
            if (ctx.Target == StoryRenderTarget.App)
            {
                // The App draws a single value — used verbatim (no per-result format needed).
                extra[token]               = !string.IsNullOrEmpty(ri.PreviewValue) ? ri.PreviewValue : range.FirstOrDefault() ?? "";
                extra["RandomInstruction"] = "";
                return ResolveText(localization, ri.AppText, ctx, errors, extra);
            }

            // Every outcome, each wrapped through the Gamebook Result Format (identity when empty), then laid out as
            // the D12 band table.
            List<string> formatted = new(range.Count);
            foreach (string value in range)
                formatted.Add(FormatGamebookResult(localization, ri, value, token, ctx, errors));

            extra[token]               = RandomBandList(localization, formatted, ri.RemainderMode);
            extra["RandomInstruction"] = StoryCommonLocalizationKeys.Resolve(localization, StoryCommonLocalizationKeys.RandomRollD12);

            return $"<randomised-instruction>{ResolveText(localization, ri.GamebookText, ctx, errors, extra)}</randomised-instruction>";
        }

        /// <summary>
        /// Wraps a single Gamebook outcome value through the node's Gamebook Result Format — e.g.
        /// <c>&lt;var={RandomResult}&gt;</c> turns each outcome into a variable pill. Verbatim when the format is empty.
        /// </summary>
        private static string FormatGamebookResult(
            LocProject? localization, StoryRandomizedInstructionNode ri, string value, string token,
            StoryVariableDictionary.Context ctx, List<string> errors)
        {
            if (ri.GamebookResultFormat.IsEmpty) return value;
            return ResolveText(localization, ri.GamebookResultFormat, ctx, errors,
                new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) { [token] = value });
        }

        /// <summary>The range a Randomized Instruction node draws from for this render — the per-branch range when a branch variable is set, else the default.</summary>
        private static List<string> RandomActiveRange(StoryProject project, StoryRandomizedInstructionNode ri, StoryVariableDictionary.Context ctx)
        {
            if (ri.BranchVariableId == Guid.Empty) return ri.DefaultRange;
            string branch = Operand(ctx, ri.BranchVariableId);
            return ri.BranchRanges.Find(r => string.Equals(r.BranchValue, branch, StringComparison.OrdinalIgnoreCase))?.Values ?? ri.DefaultRange;
        }

        /// <summary>The Gamebook D12 roll-to-outcome table for a range — one localized "rolled a–b → value" line per outcome, newline-separated.</summary>
        private static string RandomBandList(LocProject? localization, IReadOnlyList<string> range, RandomRemainderMode mode)
        {
            List<(int From, int To)> bands = D12Bands(range.Count, mode);
            StringBuilder            sb    = new();
            for (int x = 0; x < bands.Count && x < range.Count; ++x)
            {
                if (x > 0) sb.Append('\n');
                sb.Append(StoryCommonLocalizationKeys.Resolve(localization, StoryCommonLocalizationKeys.RandomRollBand,
                    new Dictionary<string, object> { ["from"] = bands[x].From, ["to"] = bands[x].To, ["value"] = range[x] }));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Splits a D12 (faces 1..12) into <paramref name="count"/> contiguous roll bands. When count divides 12 the
        /// bands are equal; otherwise <see cref="RandomRemainderMode.Reroll"/> keeps equal <c>floor(12/count)</c> bands
        /// (the top out-of-range faces are rerolled, so fewer than 12 faces are covered) and
        /// <see cref="RandomRemainderMode.Fill"/> spreads the remainder across the first bands so all twelve map.
        /// </summary>
        public static List<(int From, int To)> D12Bands(int count, RandomRemainderMode mode)
        {
            List<(int From, int To)> bands = new();
            if (count <= 0) return bands;
            if (count > 12) count = 12;

            int start = 1;
            if (12 % count == 0 || mode == RandomRemainderMode.Reroll)
            {
                int band = 12 / count;
                for (int x = 0; x < count; ++x)
                {
                    bands.Add((start, start + band - 1));
                    start += band;
                }
            }
            else
            {
                int baseSize = 12 / count;
                int rem      = 12 % count;
                for (int x = 0; x < count; ++x)
                {
                    int size = baseSize + (x < rem ? 1 : 0);
                    bands.Add((start, start + size - 1));
                    start += size;
                }
            }
            return bands;
        }

        // Matches an embedded markup/pill tag (authored HTML like <b>, or a variable/slot/icon pill like <var=Name> /
        // <slot=TA>). The case transform skips these so their tag names and by-name lookups survive up/down-casing.
        private static readonly Regex _EmbeddedTag = new Regex(@"<[^>]+>", RegexOptions.Compiled);

        /// <summary>Upper/lower-cases the plain-text runs of <paramref name="text"/>, leaving embedded <c>&lt;…&gt;</c> tags verbatim.</summary>
        private static string ApplyCasing(string text, StoryTextCasing casing)
        {
            if (casing == StoryTextCasing.None || text.Length == 0) return text;
            Func<string, string> f = casing == StoryTextCasing.Upper ? s => s.ToUpperInvariant() : s => s.ToLowerInvariant();

            StringBuilder sb   = new();
            int           last = 0;
            foreach (Match m in _EmbeddedTag.Matches(text))
            {
                sb.Append(f(text.Substring(last, m.Index - last)));
                sb.Append(m.Value);
                last = m.Index + m.Length;
            }
            sb.Append(f(text.Substring(last)));
            return sb.ToString();
        }

        /// <summary>The main-language text of the localization key <paramref name="keyId"/> (empty when unavailable).</summary>
        public static string LocalizedText(LocProject? localization, Guid keyId)
        {
            LocLocalizationKey? key = localization?.Keys.Find(k => k.Id == keyId);
            if (key is null) return "";

            string? main = localization!.Metadata.MainLanguageId;
            if (string.IsNullOrEmpty(main)) return "";
            return key.Translations.Find(t => t.LanguageId == main)?.Text ?? "";
        }

        // ── Icon resolution ──────────────────────────────────────────────────────

        /// <summary>
        /// The node's icon for this render: the theme's own slot, falling back to the other when that one is unset — so
        /// filling a single slot gives both themes the same icon.
        /// </summary>
        private static string? ResolveEntryIcon(StoryProject project, StoryLogicNode logic, bool paper)
        {
            Guid id = paper ? logic.LightIcon : logic.DarkIcon;
            if (id == Guid.Empty) id = paper ? logic.DarkIcon : logic.LightIcon;
            if (id == Guid.Empty) return null;
            return project.Images.TryGetValue(id, out StoryImage? img) ? img.Data : null;
        }
    }
}
