using System;
using System.Collections.Generic;
using System.Linq;
using DeusaldLocalizerCommon;
using JetBrains.Annotations;

namespace DeusaldStoryCommon
{
    /// <summary>
    /// Resolves a logic node's inner content graph into plain rendered data — the title, optional subtitle, an
    /// optional icon (base64 PNG), the ordered text blocks produced by walking the linear LFlow chain, and the choices
    /// its Exit node offers. Host-agnostic so the App preview, the Gamebook preview and (later) PDF export share one
    /// resolution; HTML sanitization is left to the caller (see <see cref="PreviewHtmlSanitizer"/>).
    /// </summary>
    [PublicAPI]
    public static class StoryLogicRenderer
    {
        private static readonly Dictionary<Guid, string> _EmptyValues = new();

        /// <summary>A logic node resolved to display text/icon for one combination of variable values.</summary>
        public sealed class RenderedLogic
        {
            public string       Title    { get; set; } = "";
            public string       Subtitle { get; set; } = "";
            public string?      IconData { get; set; }
            public List<string> Blocks   { get; set; } = new();

            /// <summary>The continuations offered by the node's Exit node (one per choice; one auto choice in App auto-mode).</summary>
            public List<RenderedChoice> Choices { get; set; } = new();

            /// <summary>Player-facing storage instructions generated by this node's Register/Set/Unregister ops, in flow order.</summary>
            public List<StorageInstruction> Instructions { get; set; } = new();

            /// <summary>SmartFormat render failures encountered while resolving this node's text (e.g. a Variable unavailable in the Gamebook).</summary>
            public List<string> Errors { get; set; } = new();
        }

        /// <summary>One resolved choice — its player-facing text plus how the App/Gamebook continues from it.</summary>
        public sealed class RenderedChoice
        {
            public string Text { get; set; } = "";

            /// <summary>The <see cref="StoryChoice.Id"/> this was rendered from.</summary>
            public Guid ChoiceId { get; set; }

            /// <summary>The outer connection point the story continues from — the choice's own Flow output (ManyPaths) or the node's shared VFlow output (SinglePath). Empty when unwired.</summary>
            public Guid OuterFlowOut { get; set; }
        }

        /// <summary>
        /// Resolves <paramref name="logic"/> against <paramref name="values"/> (variable id → value). <paramref name="paper"/>
        /// selects the light side of any Light/Dark switch; <paramref name="target"/> selects App vs Gamebook resolution.
        /// </summary>
        public static RenderedLogic Render(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, bool paper, StoryRenderTarget target = StoryRenderTarget.App)
        {
            List<string> errors = new();
            WalkSpine(project, localization, logic, values, target, errors, out List<string> blocks, out List<RenderedChoice> choices);
            return new RenderedLogic
            {
                Title        = ResolveText(project, localization, logic, values, FromPointInto(logic, logic.TitleIn.Id),    target, 0, errors),
                Subtitle     = ResolveText(project, localization, logic, values, FromPointInto(logic, logic.SubtitleIn.Id), target, 0, errors),
                IconData     = ResolveIconImage(project, logic, FromPointInto(logic, logic.IconIn.Id), paper, 0),
                Blocks       = blocks,
                Choices      = choices,
                Instructions = StoryStorageInstructions.For(project, localization, logic, target, values),
                Errors       = errors
            };
        }

        /// <summary>The choices the node's Exit node offers for <paramref name="target"/>.</summary>
        public static List<RenderedChoice> Choices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target = StoryRenderTarget.App)
        {
            WalkSpine(project, localization, logic, values, target, new List<string>(), out _, out List<RenderedChoice> choices);
            return choices;
        }

        /// <summary>
        /// Resolves the text wired into <paramref name="toPoint"/> (a Localization / SmartFormat output), for flow-only
        /// callers that carry no variable values — e.g. the storage-instruction generator reading a Register/Set node's
        /// Instruction port. When <paramref name="slot"/> is supplied the port's text is SmartFormatted with a
        /// <c>{slot}</c> placeholder bound to it (the storage slot label / styled pill markup).
        /// </summary>
        public static string ResolvePortText(
            StoryProject project, LocProject? localization, StoryLogicNode logic, Guid toPoint,
            StoryRenderTarget target = StoryRenderTarget.App, string? slot = null)
        {
            Dictionary<string, object>? extra = slot is null
                ? null
                : new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) { ["slot"] = slot };
            string text = ResolveText(project, localization, logic, _EmptyValues, FromPointInto(logic, toPoint), target, 0, new List<string>(), extra);
            return extra is null ? text : StoryConditionPreview.Render(text, extra, out _);
        }

        // ── LFlow chain walk ─────────────────────────────────────────────────────

        /// <summary>
        /// Walks the linear LFlow chain from the Entry, collecting the ordered text <paramref name="blocks"/> rendered
        /// by FlowText nodes (storage / set-external nodes pass straight through), then resolves the Exit node's
        /// <paramref name="choices"/>. In the App, when the Exit's Variables input is wired, the choice auto-resolves to
        /// one button via each choice's condition (Else last); otherwise every choice is a button. The Gamebook always
        /// lists every choice.
        /// </summary>
        private static void WalkSpine(
            StoryProject project, LocProject? localization, StoryLogicNode logic, IReadOnlyDictionary<Guid, string> values,
            StoryRenderTarget renderTarget, List<string> errors, out List<string> blocks, out List<RenderedChoice> choices)
        {
            blocks  = new();
            choices = new();
            Guid target = FlowTargetOf(logic, logic.EntryPoint.Id);

            for (int guard = 0; guard < 256; ++guard)
            {
                if (logic.FlowTextNodes.Find(n => n.FlowIn.Id == target) is StoryFlowTextNode ft)
                {
                    bool renderHere = renderTarget == StoryRenderTarget.App ? ft.RenderInApp : ft.RenderInGamebook;
                    if (renderHere)
                        blocks.Add(ResolveText(project, localization, logic, values, FromPointInto(logic, ft.TextIn.Id), renderTarget, 0, errors));
                    target = FlowTargetOf(logic, ft.FlowOut.Id);
                }
                else if (logic.SetExternalVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetExternalVariableNode se)
                    target = FlowTargetOf(logic, se.FlowOut.Id);
                else if (logic.RegisterVariableNodes.Find(n => n.FlowIn.Id == target) is StoryRegisterVariableNode reg)
                    target = FlowTargetOf(logic, reg.FlowOut.Id);
                else if (logic.SetVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetVariableNode set)
                    target = FlowTargetOf(logic, set.FlowOut.Id);
                else if (logic.UnregisterVariableNodes.Find(n => n.FlowIn.Id == target) is StoryUnregisterVariableNode unreg)
                    target = FlowTargetOf(logic, unreg.FlowOut.Id);
                else
                    break; // reached the Exit node's LFlow input or a leaf
            }

            choices = ResolveChoices(project, localization, logic, values, renderTarget, errors);
        }

        /// <summary>Resolves the Exit node's <see cref="StoryLogicNode.Choices"/> into rendered continuations for the medium.</summary>
        private static List<RenderedChoice> ResolveChoices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target, List<string> errors)
        {
            List<RenderedChoice> result = new();
            if (logic.Choices.Count == 0) return result;

            bool autoMode = target == StoryRenderTarget.App && FromPointInto(logic, logic.ExitVariablesIn.Id) != Guid.Empty;
            if (autoMode)
            {
                string Resolve(Guid varOut) => StoryLogicFlow.ResolveVariableValue(project, logic, varOut, values, target);
                StoryChoice? picked = logic.Choices.FirstOrDefault(c => c.IsElse || (c.Condition?.Evaluate(Resolve) ?? false));
                if (picked is not null)
                    result.Add(new RenderedChoice
                    {
                        Text         = ResolveText(project, localization, logic, values, FromPointInto(logic, logic.ExitAutoTextIn.Id), target, 0, errors),
                        ChoiceId     = picked.Id,
                        OuterFlowOut = OuterFlowOut(logic, picked)
                    });
                return result;
            }

            foreach (StoryChoice choice in logic.Choices)
                result.Add(new RenderedChoice
                {
                    Text         = ResolveText(project, localization, logic, values, FromPointInto(logic, choice.TextIn.Id), target, 0, errors),
                    ChoiceId     = choice.Id,
                    OuterFlowOut = OuterFlowOut(logic, choice)
                });
            return result;
        }

        /// <summary>The outer connection point a choice continues from — its own Flow output (ManyPaths) or the node's shared VFlow output (SinglePath).</summary>
        private static Guid OuterFlowOut(StoryLogicNode logic, StoryChoice choice) =>
            logic.ExitMode == StoryLogicExitMode.SinglePath ? logic.VFlowOut.Id : choice.OuterFlowOut.Id;

        private static Guid FlowTargetOf(StoryLogicNode logic, Guid fromPoint) =>
            logic.ContentConnections.Find(c => c.FromPoint == fromPoint)?.ToPoint ?? Guid.Empty;

        // ── Text resolution ──────────────────────────────────────────────────────

        private static string ResolveText(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, Guid fromPoint, StoryRenderTarget target, int depth,
            List<string> errors, IReadOnlyDictionary<string, object>? extraValues = null)
        {
            if (fromPoint == Guid.Empty || depth > 8) return "";

            if (logic.LocalizationNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryLocalizationNode locNode)
                return LocalizedText(localization, locNode.SelectedKeyId);

            if (logic.SmartFormatNodes.Find(n => n.OutPoint.Id == fromPoint) is StorySmartFormatNode sf)
            {
                string format = ResolveText(project, localization, logic, values, FromPointInto(logic, sf.LocalizationIn.Id), target, depth + 1, errors, extraValues);

                Dictionary<string, object> vals = new(StringComparer.OrdinalIgnoreCase);
                if (extraValues is not null)
                    foreach (KeyValuePair<string, object> kv in extraValues) vals[kv.Key] = kv.Value;

                bool hasOmittedVariable = false; // a plain Variable dropped in the Gamebook (probable SmartFormat-error cause)
                foreach (StoryConnection c in logic.ContentConnections.Where(c => c.ToPoint == sf.VariablesIn.Id))
                {
                    if (logic.ExternalVariableNodes.Find(n => n.OutPoint.Id == c.FromPoint) is StoryExternalVariableNode ev
                        && Variable(project, ev.SelectedVariableId) is StoryVariable v && !string.IsNullOrWhiteSpace(v.Name))
                    {
                        bool constant = StoryBuiltInVariables.IsBuiltIn(v.Id) || v.IsConstant;
                        if (StoryBuiltInVariables.IsBuiltIn(v.Id)) vals[v.Name] = StoryBuiltInVariables.ValueFor(target);
                        else if (constant || target == StoryRenderTarget.App) vals[v.Name] = PreviewValue(v, values);
                        else hasOmittedVariable = true; // plain Variable, Gamebook — leave the {token} unresolved
                    }
                    else if (logic.GetVariableNodes.Find(n => n.SlotOutPoint.Id == c.FromPoint) is StoryGetVariableNode gvSlot
                        && GetVariableName(project, gvSlot) is { Length: > 0 } gvSlotName)
                        vals[gvSlotName] = GetVariableSlotTag(project, gvSlot); // constant slot tag — resolves in both mediums
                    else if (logic.GetVariableNodes.Find(n => n.OutPoint.Id == c.FromPoint) is StoryGetVariableNode gv
                        && GetVariableName(project, gv) is { Length: > 0 } gvName)
                    {
                        if (target == StoryRenderTarget.App) vals[gvName] = GetVariablePreviewValue(project, gv);
                        else hasOmittedVariable = true; // live value, unknown in the Gamebook
                    }
                    else if (logic.ConstantVariableNodes.Find(n => n.OutPoint.Id == c.FromPoint) is StoryConstantVariableNode cv
                        && !string.IsNullOrWhiteSpace(cv.Name))
                        vals[cv.Name] = cv.Value;
                    else if (IncomingVariable(project, logic, c.FromPoint) is StoryDeclaredVariable dv && !string.IsNullOrWhiteSpace(dv.Name))
                        vals[dv.Name] = values.TryGetValue(c.FromPoint, out string? sel) ? sel : "";
                }

                string rendered = StoryConditionPreview.Render(format, vals, out string? error);
                if (error is not null)
                    errors.Add(hasOmittedVariable
                        ? $"SmartFormat failed to render: {error} (probable cause: a Variable is wired here and is unavailable in the Gamebook)."
                        : $"SmartFormat failed to render: {error}");
                return rendered;
            }

            return "";
        }

        /// <summary>The upstream declared variable (a Prev Exit Variable output) identified by <paramref name="fromPoint"/>, or null.</summary>
        private static StoryDeclaredVariable? IncomingVariable(StoryProject project, StoryLogicNode logic, Guid fromPoint)
        {
            if (!logic.AcceptVariables) return null;
            return StorySelectionResolver.IncomingVariables(project, logic).Find(d => d.Id == fromPoint);
        }

        /// <summary>The main-language text of the localization key <paramref name="keyId"/> (empty when unavailable).</summary>
        public static string LocalizedText(LocProject? localization, Guid keyId)
        {
            LocLocalizationKey? key = localization?.Keys.Find(k => k.Id == keyId);
            if (key is null) return "";

            string? main = localization!.Metadata.MainLanguageId;
            if (string.IsNullOrEmpty(main)) return "";
            return key.Translations.Find(t => t.LanguageId == main)?.Text ?? "";
        }

        private static string PreviewValue(StoryVariable v, IReadOnlyDictionary<Guid, string> values) =>
            values.TryGetValue(v.Id, out string? val) ? val : v.PossibleValues.FirstOrDefault() ?? "";

        private static StoryVariable? Variable(StoryProject project, Guid id) =>
            StoryBuiltInVariables.Find(id)
            ?? (id != Guid.Empty && project.Variables.TryGetValue(id, out StoryVariable? v) ? v : null);

        /// <summary>The SmartFormat token name a Get Variable node supplies under — its override, else the register's own name (empty when unresolved).</summary>
        private static string GetVariableName(StoryProject project, StoryGetVariableNode gv)
        {
            if (!string.IsNullOrWhiteSpace(gv.NameOverride)) return gv.NameOverride;
            return FindRegister(project, gv.RegisteredVariableId)?.Name ?? "";
        }

        /// <summary>The App-preview value for a Get Variable node — its own preview value, falling back to the register's when blank.</summary>
        private static string GetVariablePreviewValue(StoryProject project, StoryGetVariableNode gv) =>
            !string.IsNullOrEmpty(gv.PreviewValue)
                ? gv.PreviewValue
                : FindRegister(project, gv.RegisteredVariableId)?.PreviewValue ?? "";

        /// <summary>The Gamebook substitution for a Get Variable node's slot port — the referenced slot's styled tag (TA/NA/DA pill).</summary>
        private static string GetVariableSlotTag(StoryProject project, StoryGetVariableNode gv)
        {
            StoryRegisterVariableNode? reg = FindRegister(project, gv.RegisteredVariableId);
            if (reg is null) return "";
            return string.IsNullOrWhiteSpace(reg.Name)
                ? PreviewHtmlSanitizer.SlotTag(StorageSlots.Label(reg.Type, reg.SlotIndex))
                : $"<var={reg.Name}>";
        }

        /// <summary>Finds a registered storage variable (a Register node) anywhere in the project by its id.</summary>
        private static StoryRegisterVariableNode? FindRegister(StoryProject project, Guid id)
        {
            if (id == Guid.Empty) return null;
            foreach (StoryLogicNode l in project.LogicNodes.Values)
                if (l.RegisterVariableNodes.Find(n => n.Id == id) is StoryRegisterVariableNode found)
                    return found;
            return null;
        }

        // ── Icon resolution ──────────────────────────────────────────────────────

        private static string? ResolveIconImage(StoryProject project, StoryLogicNode logic, Guid fromPoint, bool paper, int depth)
        {
            if (fromPoint == Guid.Empty || depth > 8) return null;

            if (logic.IconNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryIconNode icon)
                return project.Images.TryGetValue(icon.SelectedImageId, out StoryImage? img) ? img.Data : null;

            if (logic.LightDarkSwitchNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryLightDarkSwitchNode sw)
            {
                Guid input = paper ? sw.LightIn.Id : sw.DarkIn.Id;
                return ResolveIconImage(project, logic, FromPointInto(logic, input), paper, depth + 1);
            }

            return null;
        }

        /// <summary>The output point wired into <paramref name="toPoint"/>, or empty when nothing is connected.</summary>
        private static Guid FromPointInto(StoryLogicNode logic, Guid toPoint) =>
            logic.ContentConnections.Find(c => c.ToPoint == toPoint)?.FromPoint ?? Guid.Empty;
    }
}
