using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DeusaldLocalizerCommon;
using JetBrains.Annotations;

namespace DeusaldStoryCommon
{
    /// <summary>
    /// Resolves a logic node's inner content graph into plain rendered data — the title, optional subtitle, an
    /// optional icon (base64 PNG), the ordered text blocks produced by walking the linear LFlow chain, and the choices
    /// its Exit node offers. Host-agnostic so the App preview, the Gamebook preview and (later) PDF export share one
    /// resolution; HTML sanitization is left to the caller (see <see cref="PreviewHtmlSanitizer"/>).
    /// </summary>
    [PublicAPI]
    public static class StoryLogicRenderer
    {
        private static readonly Dictionary<Guid, string> _EmptyValues = new();

        /// <summary>A logic node resolved to display text/icon for one combination of variable values.</summary>
        public sealed class RenderedLogic
        {
            public string       Title    { get; set; } = "";
            public string       Subtitle { get; set; } = "";
            public string?      IconData { get; set; }

            /// <summary>Every text block in flow order (all App pages concatenated). The Gamebook renders this as one continuous section.</summary>
            public List<RenderedBlock> Blocks   { get; set; } = new();

            /// <summary>The App-only paging of the content — one entry per "Click here to continue…" screen (see <see cref="RenderedPage"/>). Empty for the Gamebook.</summary>
            public List<RenderedPage> Pages { get; set; } = new();

            /// <summary>The continuations offered by the node's Exit node (one per choice; one auto choice in App auto-mode).</summary>
            public List<RenderedChoice> Choices { get; set; } = new();

            /// <summary>
            /// App-only, Hub Paths mode — one entry per visible choice, carrying the inline-rendered destination node so
            /// the preview draws it as a sub-card. Empty in every other mode / medium.
            /// </summary>
            public List<RenderedSubHub> SubHubs { get; set; } = new();

            /// <summary>Player-facing storage instructions generated by this node's Register/Set/Unregister ops, in flow order.</summary>
            public List<StorageInstruction> Instructions { get; set; } = new();

            /// <summary>SmartFormat render failures encountered while resolving this node's text (e.g. a Variable unavailable in the Gamebook).</summary>
            public List<string> Errors { get; set; } = new();
        }

        /// <summary>
        /// One App "page" — the content shown on a single screen, ending in a "Click here to continue…" button (or the
        /// exit choices on the last page). A Split-for-App node on the flow spine starts a new page; input fields land on
        /// the page whose flow segment contains them, positioned above or below that page's text by their own placement.
        /// </summary>
        public sealed class RenderedPage
        {
            public List<StorageInstruction> Above  { get; set; } = new();
            public List<RenderedBlock>      Blocks { get; set; } = new();
            public List<StorageInstruction> Below  { get; set; } = new();
        }

        /// <summary>One rendered text block — the resolved (sanitizable) text plus the frame style it is drawn in.</summary>
        public sealed class RenderedBlock
        {
            public RenderedBlock() { }
            public RenderedBlock(string text, StoryTextFrameStyle frameStyle)
            {
                Text       = text;
                FrameStyle = frameStyle;
            }
            public string              Text       { get; set; } = "";
            public StoryTextFrameStyle FrameStyle { get; set; } = StoryTextFrameStyle.Normal;
        }

        /// <summary>One resolved choice — its player-facing text plus how the App/Gamebook continues from it.</summary>
        public sealed class RenderedChoice
        {
            public string Text { get; set; } = "";

            /// <summary>The <see cref="StoryChoice.Id"/> this was rendered from.</summary>
            public Guid ChoiceId { get; set; }

            /// <summary>The outer connection point the story continues from — the choice's own Flow output (ManyPaths) or the node's shared VFlow output (SinglePath). Empty when unwired.</summary>
            public Guid OuterFlowOut { get; set; }
        }

        /// <summary>
        /// One Hub Paths sub-card — a visible choice whose destination logic node is rendered inline. <see cref="Link"/>
        /// is the choice used to navigate into it; <see cref="Content"/> is the destination's rendered content (null when
        /// the destination is the story End, dangling or unwired — see <see cref="Status"/>).
        /// </summary>
        public sealed class RenderedSubHub
        {
            public RenderedChoice                    Link    { get; set; } = new();
            public RenderedLogic?                    Content { get; set; }
            public StoryFlowNavigator.NextKind       Status  { get; set; } = StoryFlowNavigator.NextKind.Dangling;

            /// <summary>The destination logic node's id (Empty for End/dangling/unwired). Used to spot a hub pointing at itself.</summary>
            public Guid TargetLogicId { get; set; }
        }

        /// <summary>
        /// Resolves <paramref name="logic"/> against <paramref name="values"/> (variable id → value). <paramref name="paper"/>
        /// selects the light side of any Light/Dark switch; <paramref name="target"/> selects App vs Gamebook resolution.
        /// </summary>
        public static RenderedLogic Render(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, bool paper, StoryRenderTarget target = StoryRenderTarget.App,
            bool renderSubHubs = true)
        {
            // Seed the built-in AppTheme value from the render's theme flag so every sub-resolver (text, choices,
            // conditions, instructions) reads it like an ordinary pinned External Variable value — Light in the
            // always-light Gamebook, else the App preview's toggle (paper = the light/paper theme).
            values = new Dictionary<Guid, string>(values)
            {
                [StoryBuiltInVariables.AppThemeId] = paper ? StoryBuiltInVariables.LightValue : StoryBuiltInVariables.DarkValue
            };

            List<string>         errors  = new();
            List<RenderedChoice> choices = ResolveChoices(project, localization, logic, values, target, errors);

            // The App pages the content into "Click here to continue…" screens at each Split-for-App node; the Gamebook
            // ignores splits and reads as one continuous block. Blocks (flat) stays populated for both mediums.
            List<RenderedPage>  pages;
            List<RenderedBlock> blocks;
            if (target == StoryRenderTarget.App)
            {
                pages  = BuildAppPages(project, localization, logic, values, errors);
                blocks = pages.SelectMany(p => p.Blocks).ToList();
            }
            else
            {
                blocks = WalkTextBlocks(project, localization, logic, values, target, errors);
                pages  = new();
            }

            // Hub Paths (App only) — render each visible choice's destination inline as a sub-card. renderSubHubs is
            // passed false into the nested render so a hub pointing at another hub cannot recurse past one level.
            List<RenderedSubHub> subHubs = target == StoryRenderTarget.App && logic.ExitMode == StoryLogicExitMode.HubPaths && renderSubHubs
                ? BuildSubHubs(project, localization, choices, paper)
                : new();

            return new RenderedLogic
            {
                Title        = ResolveText(project, localization, logic, values, FromPointInto(logic, logic.TitleIn.Id),    target, 0, errors),
                Subtitle     = ResolveText(project, localization, logic, values, FromPointInto(logic, logic.SubtitleIn.Id), target, 0, errors),
                IconData     = ResolveIconImage(project, logic, FromPointInto(logic, logic.IconIn.Id), paper, 0),
                Blocks       = blocks,
                Pages        = pages,
                Choices      = choices,
                SubHubs      = subHubs,
                Instructions = StoryStorageInstructions.For(project, localization, logic, target, values),
                Errors       = errors
            };
        }

        /// <summary>
        /// Builds a Hub Paths sub-card per already-visible choice: resolves where the choice leads and, when it reaches
        /// another logic node, renders that node's content inline (with its own sub-hubs suppressed, bounding recursion).
        /// A fresh navigation seeds no live variables, so sub-card content is resolved against an empty value set.
        /// </summary>
        private static List<RenderedSubHub> BuildSubHubs(StoryProject project, LocProject? localization, List<RenderedChoice> choices, bool paper)
        {
            List<RenderedSubHub> result = new();
            foreach (RenderedChoice choice in choices)
            {
                if (choice.OuterFlowOut == Guid.Empty)
                {
                    result.Add(new RenderedSubHub { Link = choice, Content = null, Status = StoryFlowNavigator.NextKind.Dangling });
                    continue;
                }
                StoryFlowNavigator.NextLogicResult next = StoryFlowNavigator.ResolveNextLogic(project, choice.OuterFlowOut);
                result.Add(new RenderedSubHub
                {
                    Link          = choice,
                    Status        = next.Kind,
                    TargetLogicId = next.Logic?.Id ?? Guid.Empty,
                    Content = next.Kind == StoryFlowNavigator.NextKind.Logic && next.Logic is not null
                        ? Render(project, localization, next.Logic, _EmptyValues, paper, StoryRenderTarget.App, renderSubHubs: false)
                        : null
                });
            }
            return result;
        }

        /// <summary>The choices the node's Exit node offers for <paramref name="target"/>.</summary>
        public static List<RenderedChoice> Choices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target = StoryRenderTarget.App) =>
            ResolveChoices(project, localization, logic, values, target, new List<string>());

        /// <summary>
        /// Resolves the text wired into <paramref name="toPoint"/> (a Localization / SmartFormat output), for flow-only
        /// callers that carry no variable values — e.g. the storage-instruction generator reading a Register/Set node's
        /// Instruction port. When <paramref name="slot"/> is supplied the port's text is SmartFormatted with the slot
        /// label / styled pill markup bound to a placeholder named <paramref name="slotToken"/> (typically
        /// <c>{&lt;Name&gt;Slot}</c>); it falls back to <c>{slot}</c> only when no token name is given (an unnamed variable).
        /// </summary>
        public static string ResolvePortText(
            StoryProject project, LocProject? localization, StoryLogicNode logic, Guid toPoint,
            StoryRenderTarget target = StoryRenderTarget.App, string? slot = null, string? slotToken = null)
        {
            Dictionary<string, object>? extra = null;
            if (slot is not null)
            {
                // A named variable's slot is referenced as {<Name>Slot} (mirrors the Get Variable slot token so the
                // whole editor references a slot the same way); {slot} only covers an unnamed variable's fallback.
                string key = string.IsNullOrWhiteSpace(slotToken) ? "slot" : slotToken;
                extra = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) { [key] = slot };
            }
            string text = ResolveText(project, localization, logic, _EmptyValues, FromPointInto(logic, toPoint), target, 0, new List<string>(), extra);
            return extra is null ? text : StoryConditionPreview.Render(text, extra, out _);
        }

        // ── LFlow chain walk ─────────────────────────────────────────────────────

        /// <summary>
        /// Walks the linear LFlow chain from the Entry, collecting the ordered text blocks rendered by FlowText nodes
        /// (storage / set-external / split nodes pass straight through). A block whose FlowText is switched off for
        /// <paramref name="renderTarget"/> is skipped. Split-for-App nodes have no effect here — they are an App-only
        /// concern handled by <see cref="BuildAppPages"/>; the Gamebook reads the whole chain as one block list.
        /// </summary>
        private static List<RenderedBlock> WalkTextBlocks(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget renderTarget, List<string> errors)
        {
            List<RenderedBlock> blocks  = new();
            HashSet<Guid>       visited = new(); // flow-in points already walked (cycle guard; also bounds condition recursion)

            // A Condition node detours into its "condition true" block (up to the paired End node) when the condition
            // holds, then continues from its "continue" output. Recursion handles nesting; the shared visited set stops cycles.
            void Walk(Guid target)
            {
                for (int guard = 0; guard < 256; ++guard)
                {
                    if (target == Guid.Empty || !visited.Add(target)) break;
                    if (logic.FlowTextNodes.Find(n => n.FlowIn.Id == target) is StoryFlowTextNode ft)
                    {
                        bool renderHere = renderTarget == StoryRenderTarget.App ? ft.RenderInApp : ft.RenderInGamebook;
                        if (renderHere)
                            blocks.Add(new RenderedBlock(ResolveText(project, localization, logic, values, FromPointInto(logic, ft.TextIn.Id), renderTarget, 0, errors), ft.FrameStyle));
                        target = FlowTargetOf(logic, ft.FlowOut.Id);
                    }
                    else if (logic.SplitForAppNodes.Find(n => n.FlowIn.Id == target) is StorySplitForAppNode split)
                        target = FlowTargetOf(logic, split.FlowOut.Id);
                    else if (logic.SetExternalVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetExternalVariableNode se)
                        target = FlowTargetOf(logic, se.FlowOut.Id);
                    else if (logic.RegisterVariableNodes.Find(n => n.FlowIn.Id == target) is StoryRegisterVariableNode reg)
                        target = FlowTargetOf(logic, reg.FlowOut.Id);
                    else if (logic.SetVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetVariableNode set)
                        target = FlowTargetOf(logic, set.FlowOut.Id);
                    else if (logic.UnregisterVariableNodes.Find(n => n.FlowIn.Id == target) is StoryUnregisterVariableNode unreg)
                        target = FlowTargetOf(logic, unreg.FlowOut.Id);
                    else if (logic.ConditionFlowNodes.Find(n => n.FlowIn.Id == target) is StoryConditionFlowNode cf)
                    {
                        if (StoryLogicFlow.EvaluateConditionFlow(project, logic, cf, values, renderTarget))
                            Walk(FlowTargetOf(logic, cf.ConditionTrueOut.Id));
                        target = FlowTargetOf(logic, cf.ContinueOut.Id);
                    }
                    else
                        break; // reached the Exit node's LFlow input, an End-condition node, or a leaf
                }
            }

            Walk(FlowTargetOf(logic, logic.EntryPoint.Id));
            return blocks;
        }

        /// <summary>
        /// Builds the App's "Click here to continue…" pages by walking the flow spine once: FlowText blocks and the
        /// input fields produced by Register / Set nodes are collected in flow order onto the current page, a
        /// Split-for-App node starts a new page, and each input lands above or below its page's text by its own
        /// placement. Storage nodes left off the chain still surface their input on the last page. Fully empty pages
        /// (a split at an edge or back-to-back splits) are dropped; at least one page is always returned.
        /// </summary>
        private static List<RenderedPage> BuildAppPages(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, List<string> errors)
        {
            List<RenderedPage> pages   = new() { new() };
            HashSet<Guid>      visited = new(); // storage nodes already emitted on the spine
            HashSet<Guid>      seen    = new(); // flow-in points already walked (cycle guard; also bounds condition recursion)

            void AddInput(RenderedPage page, StorageInstruction? entry)
            {
                if (entry is not { IsAppInput: true }) return; // the App surfaces only player-input fields
                (entry.Placement == StorageInstructionPlacement.Above ? page.Above : page.Below).Add(entry);
            }

            // A Condition node detours into its "condition true" block (up to the paired End node) when the condition
            // holds, then continues from its "continue" output; a Split inside the block still breaks the App into pages.
            void Walk(Guid target)
            {
                for (int guard = 0; guard < 256; ++guard)
                {
                    if (target == Guid.Empty || !seen.Add(target)) break;
                    RenderedPage page = pages[^1];
                    if (logic.FlowTextNodes.Find(n => n.FlowIn.Id == target) is StoryFlowTextNode ft)
                    {
                        if (ft.RenderInApp)
                            page.Blocks.Add(new RenderedBlock(ResolveText(project, localization, logic, values, FromPointInto(logic, ft.TextIn.Id), StoryRenderTarget.App, 0, errors), ft.FrameStyle));
                        target = FlowTargetOf(logic, ft.FlowOut.Id);
                    }
                    else if (logic.SplitForAppNodes.Find(n => n.FlowIn.Id == target) is StorySplitForAppNode split)
                    {
                        pages.Add(new());
                        target = FlowTargetOf(logic, split.FlowOut.Id);
                    }
                    else if (logic.RegisterVariableNodes.Find(n => n.FlowIn.Id == target) is StoryRegisterVariableNode reg)
                    {
                        AddInput(page, StoryStorageInstructions.ForOp(project, localization, logic, StorageOp.For(reg), StoryRenderTarget.App));
                        visited.Add(reg.Id);
                        target = FlowTargetOf(logic, reg.FlowOut.Id);
                    }
                    else if (logic.SetVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetVariableNode set)
                    {
                        AddInput(page, StoryStorageInstructions.ForOp(project, localization, logic, StorageOp.For(project, logic, set, values, StoryRenderTarget.App), StoryRenderTarget.App));
                        visited.Add(set.Id);
                        target = FlowTargetOf(logic, set.FlowOut.Id);
                    }
                    else if (logic.UnregisterVariableNodes.Find(n => n.FlowIn.Id == target) is StoryUnregisterVariableNode unreg)
                    {
                        visited.Add(unreg.Id); // the App drops the value silently — no input field
                        target = FlowTargetOf(logic, unreg.FlowOut.Id);
                    }
                    else if (logic.SetExternalVariableNodes.Find(n => n.FlowIn.Id == target) is StorySetExternalVariableNode se)
                        target = FlowTargetOf(logic, se.FlowOut.Id);
                    else if (logic.ConditionFlowNodes.Find(n => n.FlowIn.Id == target) is StoryConditionFlowNode cf)
                    {
                        if (StoryLogicFlow.EvaluateConditionFlow(project, logic, cf, values, StoryRenderTarget.App))
                            Walk(FlowTargetOf(logic, cf.ConditionTrueOut.Id));
                        target = FlowTargetOf(logic, cf.ContinueOut.Id);
                    }
                    else
                        break; // reached the Exit node's LFlow input, an End-condition node, or a leaf
                }
            }

            Walk(FlowTargetOf(logic, logic.EntryPoint.Id));

            // Storage nodes dropped in but left unwired still run when the story visits the node — surface their input
            // on the last page (they have no flow position of their own). Mirrors StoryLogicFlow's unwired-tail append.
            RenderedPage last = pages[^1];
            bool Wired(StoryConnectionPoint flowIn, StoryConnectionPoint flowOut) =>
                logic.ContentConnections.Exists(c => c.ToPoint == flowIn.Id || c.FromPoint == flowOut.Id);
            foreach (StoryRegisterVariableNode reg in logic.RegisterVariableNodes)
                if (!visited.Contains(reg.Id) && !Wired(reg.FlowIn, reg.FlowOut))
                    AddInput(last, StoryStorageInstructions.ForOp(project, localization, logic, StorageOp.For(reg), StoryRenderTarget.App));
            foreach (StorySetVariableNode set in logic.SetVariableNodes)
                if (!visited.Contains(set.Id) && !Wired(set.FlowIn, set.FlowOut))
                    AddInput(last, StoryStorageInstructions.ForOp(project, localization, logic, StorageOp.For(project, logic, set, values, StoryRenderTarget.App), StoryRenderTarget.App));

            pages.RemoveAll(p => p.Above.Count == 0 && p.Blocks.Count == 0 && p.Below.Count == 0);
            if (pages.Count == 0) pages.Add(new());
            return pages;
        }

        /// <summary>Resolves the Exit node's <see cref="StoryLogicNode.Choices"/> into rendered continuations for the medium.</summary>
        private static List<RenderedChoice> ResolveChoices(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target, List<string> errors)
        {
            List<RenderedChoice> result = new();
            if (logic.Choices.Count == 0) return result;

            // Auto-resolution is App-only and needs a variable wired into the Exit node. Hub Paths always uses
            // Choice Visibility; otherwise the node's own ExitAutoMode decides.
            bool varsWired = target == StoryRenderTarget.App && FromPointInto(logic, logic.ExitVariablesIn.Id) != Guid.Empty;
            StoryExitAutoMode mode = logic.ExitMode == StoryLogicExitMode.HubPaths ? StoryExitAutoMode.ChoiceVisibility : logic.ExitAutoMode;

            if (varsWired && mode == StoryExitAutoMode.AutomaticChoice)
            {
                string Resolve(Guid varOut) => StoryLogicFlow.ResolveVariableValue(project, logic, varOut, values, target);
                StoryChoice? picked = logic.Choices.FirstOrDefault(c => c.IsElse || (c.Condition?.Evaluate(Resolve) ?? false));
                if (picked is not null)
                    result.Add(new RenderedChoice
                    {
                        Text         = ResolveText(project, localization, logic, values, FromPointInto(logic, logic.ExitAutoTextIn.Id), target, 0, errors),
                        ChoiceId     = picked.Id,
                        OuterFlowOut = OuterFlowOut(logic, picked)
                    });
                return result;
            }

            // Choice Visibility (App, vars wired) — show each choice only when its condition is empty (always) or true.
            // An empty Group evaluates true, so the "empty ⇒ always shown" rule collapses to `?? true`.
            if (varsWired && mode == StoryExitAutoMode.ChoiceVisibility)
            {
                string Resolve(Guid varOut) => StoryLogicFlow.ResolveVariableValue(project, logic, varOut, values, target);
                foreach (StoryChoice choice in logic.Choices)
                {
                    if (!(choice.Condition?.Evaluate(Resolve) ?? true)) continue;
                    result.Add(new RenderedChoice
                    {
                        Text         = ResolveText(project, localization, logic, values, FromPointInto(logic, choice.TextIn.Id), target, 0, errors),
                        ChoiceId     = choice.Id,
                        OuterFlowOut = OuterFlowOut(logic, choice)
                    });
                }
                return result;
            }

            foreach (StoryChoice choice in logic.Choices)
                result.Add(new RenderedChoice
                {
                    Text         = ResolveText(project, localization, logic, values, FromPointInto(logic, choice.TextIn.Id), target, 0, errors),
                    ChoiceId     = choice.Id,
                    OuterFlowOut = OuterFlowOut(logic, choice)
                });
            return result;
        }

        /// <summary>The outer connection point a choice continues from — its own Flow output (ManyPaths) or the node's shared VFlow output (SinglePath).</summary>
        private static Guid OuterFlowOut(StoryLogicNode logic, StoryChoice choice) =>
            logic.ExitMode == StoryLogicExitMode.SinglePath ? logic.VFlowOut.Id : choice.OuterFlowOut.Id;

        private static Guid FlowTargetOf(StoryLogicNode logic, Guid fromPoint) =>
            logic.ContentConnections.Find(c => c.FromPoint == fromPoint)?.ToPoint ?? Guid.Empty;

        // ── Text resolution ──────────────────────────────────────────────────────

        private static string ResolveText(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, Guid fromPoint, StoryRenderTarget target, int depth,
            List<string> errors, IReadOnlyDictionary<string, object>? extraValues = null)
        {
            if (fromPoint == Guid.Empty || depth > 8) return "";

            if (logic.LocalizationNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryLocalizationNode locNode)
                return LocalizedText(localization, locNode.SelectedKeyId);

            // A Constant String is a literal text source — returned verbatim so any placeholder tokens the author typed
            // (e.g. {RandomResult}) survive to be substituted by whatever consumes the wire.
            if (logic.ConstantStringNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryConstantStringNode constStr)
                return constStr.Value;

            if (logic.SmartFormatNodes.Find(n => n.OutPoint.Id == fromPoint) is StorySmartFormatNode sf)
            {
                string format = ResolveText(project, localization, logic, values, FromPointInto(logic, sf.LocalizationIn.Id), target, depth + 1, errors, extraValues);

                Dictionary<string, object> vals = new(StringComparer.OrdinalIgnoreCase);
                if (extraValues is not null)
                    foreach (KeyValuePair<string, object> kv in extraValues) vals[kv.Key] = kv.Value;

                bool hasOmittedVariable = false; // a plain Variable dropped in the Gamebook (probable SmartFormat-error cause)
                foreach (StoryConnection c in logic.ContentConnections.Where(c => c.ToPoint == sf.VariablesIn.Id))
                {
                    // A variable may reach the format via a portal — resolve the wire back to the real value source first.
                    Guid src = logic.ResolvePortalSource(c.FromPoint);
                    if (logic.ExternalVariableNodes.Find(n => n.OutPoint.Id == src) is StoryExternalVariableNode ev
                        && Variable(project, ev.SelectedVariableId) is StoryVariable v && !string.IsNullOrWhiteSpace(v.Name))
                    {
                        bool constant = StoryBuiltInVariables.IsBuiltIn(v.Id) || v.IsConstant;
                        if (StoryBuiltInVariables.IsBuiltIn(v.Id)) vals[v.Name] = StoryBuiltInVariables.ValueFor(v.Id, target, values);
                        else if (constant || target == StoryRenderTarget.App) vals[v.Name] = PreviewValue(v, values);
                        else hasOmittedVariable = true; // plain Variable, Gamebook — leave the {token} unresolved
                    }
                    else if (logic.GetVariableNodes.Find(n => n.SlotOutPoint.Id == src) is StoryGetVariableNode gvSlot
                        && GetVariableSlotName(project, logic, gvSlot, values, target) is { Length: > 0 } gvSlotName)
                        vals[gvSlotName] = GetVariableSlotTag(project, logic, gvSlot, values, target); // constant slot tag — resolves in both mediums
                    else if (logic.GetVariableNodes.Find(n => n.OutPoint.Id == src) is StoryGetVariableNode gv
                        && GetVariableName(project, logic, gv, values, target) is { Length: > 0 } gvName)
                    {
                        if (target == StoryRenderTarget.App) vals[gvName] = GetVariablePreviewValue(project, logic, gv, values, target);
                        else hasOmittedVariable = true; // live value, unknown in the Gamebook
                    }
                    else if (logic.ConstantVariableNodes.Find(n => n.OutPoint.Id == src) is StoryConstantVariableNode cv
                        && !string.IsNullOrWhiteSpace(cv.Name))
                        vals[cv.Name] = cv.Value;
                    else if (logic.RandomizedInstructionNodes.Find(n => n.OutVariable.Id == src) is StoryRandomizedInstructionNode riVar
                        && !string.IsNullOrWhiteSpace(riVar.ResultToken))
                    {
                        if (target == StoryRenderTarget.App)
                            vals[riVar.ResultToken.Trim()] = !string.IsNullOrEmpty(riVar.PreviewValue)
                                ? riVar.PreviewValue
                                : RandomActiveRange(project, logic, riVar, values, target).FirstOrDefault() ?? "";
                        else hasOmittedVariable = true; // live App-drawn value, unknown in the Gamebook
                    }
                    else if (IncomingVariable(project, logic, src) is StoryDeclaredVariable dv && !string.IsNullOrWhiteSpace(dv.Name))
                        vals[dv.Name] = StorySelectionResolver.IncomingValue(project, logic, src, values);
                }

                string rendered = StoryConditionPreview.Render(format, vals, out string? error);
                if (error is not null)
                    errors.Add(hasOmittedVariable
                        ? UiLang.T(Localization.Services.Renderer.smartFormatFailedGamebook, new Dictionary<string, object> { ["error"] = error })
                        : UiLang.T(Localization.Services.Renderer.smartFormatFailed,         new Dictionary<string, object> { ["error"] = error }));
                return ApplySmartFormatTransforms(sf, rendered);
            }

            if (logic.RandomizedInstructionNodes.Find(n => n.OutText.Id == fromPoint) is StoryRandomizedInstructionNode ri)
            {
                Guid   fmtPort = target == StoryRenderTarget.App ? ri.AppTextIn.Id : ri.GamebookTextIn.Id;
                string format  = ResolveText(project, localization, logic, values, FromPointInto(logic, fmtPort), target, depth + 1, errors, extraValues);

                Dictionary<string, object> tokens = new(StringComparer.OrdinalIgnoreCase);
                if (extraValues is not null)
                    foreach (KeyValuePair<string, object> kv in extraValues) tokens[kv.Key] = kv.Value;

                List<string> range     = RandomActiveRange(project, logic, ri, values, target);
                string       tokenName = string.IsNullOrWhiteSpace(ri.ResultToken) ? "RandomResult" : ri.ResultToken.Trim();
                if (target == StoryRenderTarget.App)
                {
                    // The App draws a single value — used verbatim (no per-result format needed).
                    tokens[tokenName]           = !string.IsNullOrEmpty(ri.PreviewValue) ? ri.PreviewValue : range.FirstOrDefault() ?? "";
                    tokens["RandomInstruction"] = "";
                }
                else
                {
                    // Every outcome, each wrapped through the Gamebook Result Format (identity when unwired), then laid out as the D12 band table.
                    List<string> formatted = new(range.Count);
                    foreach (string value in range)
                        formatted.Add(FormatGamebookResult(project, localization, logic, values, ri, value, tokenName, depth, errors, extraValues));
                    tokens[tokenName]           = RandomBandList(localization, formatted, ri.RemainderMode);
                    tokens["RandomInstruction"] = StoryCommonLocalizationKeys.Resolve(localization, StoryCommonLocalizationKeys.RandomRollD12);
                }

                string rendered = StoryConditionPreview.Render(format, tokens, out string? error);
                if (error is not null)
                    errors.Add(UiLang.T(Localization.Services.Renderer.smartFormatFailed, new Dictionary<string, object> { ["error"] = error }));
                return target == StoryRenderTarget.Gamebook ? $"<randomised-instruction>{rendered}</randomised-instruction>" : rendered;
            }

            return "";
        }

        /// <summary>
        /// Wraps a single Gamebook outcome value through the node's Gamebook Result Format input — the wired text
        /// (typically a Constant String) with the <see cref="StoryRandomizedInstructionNode.ResultToken"/> placeholder
        /// substituted for the value. Returns the value verbatim when the format input is unwired.
        /// </summary>
        private static string FormatGamebookResult(
            StoryProject project, LocProject? localization, StoryLogicNode logic,
            IReadOnlyDictionary<Guid, string> values, StoryRandomizedInstructionNode ri, string value, string tokenName,
            int depth, List<string> errors, IReadOnlyDictionary<string, object>? extraValues)
        {
            string format = ResolveText(project, localization, logic, values, FromPointInto(logic, ri.GamebookResultFormat.Id), StoryRenderTarget.Gamebook, depth + 1, errors, extraValues);
            if (string.IsNullOrEmpty(format)) return value;

            Dictionary<string, object> tokens   = new(StringComparer.OrdinalIgnoreCase) { [tokenName] = value };
            string                     rendered = StoryConditionPreview.Render(format, tokens, out string? error);
            if (error is not null)
                errors.Add(UiLang.T(Localization.Services.Renderer.smartFormatFailed, new Dictionary<string, object> { ["error"] = error }));
            return rendered;
        }

        /// <summary>The range a Randomized Instruction node draws from for this render — the per-branch range when Branch is wired, else the default.</summary>
        private static List<string> RandomActiveRange(
            StoryProject project, StoryLogicNode logic, StoryRandomizedInstructionNode ri,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target)
        {
            Guid branchFrom = FromPointInto(logic, ri.BranchIn.Id);
            if (branchFrom == Guid.Empty) return ri.DefaultRange;
            string branch = StoryLogicFlow.ResolveVariableValue(project, logic, branchFrom, values, target);
            return ri.BranchRanges.Find(r => string.Equals(r.BranchValue, branch, StringComparison.OrdinalIgnoreCase))?.Values ?? ri.DefaultRange;
        }

        /// <summary>The Gamebook D12 roll-to-outcome table for a range — one localized "rolled a–b → value" line per outcome, newline-separated.</summary>
        private static string RandomBandList(LocProject? localization, IReadOnlyList<string> range, RandomRemainderMode mode)
        {
            List<(int From, int To)> bands = D12Bands(range.Count, mode);
            StringBuilder            sb    = new();
            for (int i = 0; i < bands.Count && i < range.Count; ++i)
            {
                if (i > 0) sb.Append('\n');
                sb.Append(StoryCommonLocalizationKeys.Resolve(localization, StoryCommonLocalizationKeys.RandomRollBand,
                    new Dictionary<string, object> { ["from"] = bands[i].From, ["to"] = bands[i].To, ["value"] = range[i] }));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Splits a D12 (faces 1..12) into <paramref name="count"/> contiguous roll bands. When count divides 12 the
        /// bands are equal; otherwise <see cref="RandomRemainderMode.Reroll"/> keeps equal <c>floor(12/count)</c> bands
        /// (the top out-of-range faces are rerolled, so fewer than 12 faces are covered) and
        /// <see cref="RandomRemainderMode.Fill"/> spreads the remainder across the first bands so all twelve map.
        /// </summary>
        public static List<(int From, int To)> D12Bands(int count, RandomRemainderMode mode)
        {
            List<(int From, int To)> bands = new();
            if (count <= 0) return bands;
            if (count > 12) count = 12;

            int start = 1;
            if (12 % count == 0 || mode == RandomRemainderMode.Reroll)
            {
                int band = 12 / count;
                for (int i = 0; i < count; ++i)
                {
                    bands.Add((start, start + band - 1));
                    start += band;
                }
            }
            else
            {
                int baseSize = 12 / count;
                int rem      = 12 % count;
                for (int i = 0; i < count; ++i)
                {
                    int size = baseSize + (i < rem ? 1 : 0);
                    bands.Add((start, start + size - 1));
                    start += size;
                }
            }
            return bands;
        }

        // Matches an embedded markup/pill tag (authored HTML like <b>, or a variable/slot/icon pill like <var=Name> /
        // <slot=TA>). The case transform skips these so their tag names and by-name lookups survive up/down-casing.
        private static readonly Regex _EmbeddedTag = new Regex(@"<[^>]+>", RegexOptions.Compiled);

        /// <summary>
        /// Applies a SmartFormat node's output settings: first the letter-case transform on the formatted result
        /// (only its plain text — embedded tags are left untouched), then the literal
        /// <see cref="StorySmartFormatNode.Prefix"/> / <see cref="StorySmartFormatNode.Suffix"/> wrapped around it
        /// (added verbatim, unaffected by the casing).
        /// </summary>
        private static string ApplySmartFormatTransforms(StorySmartFormatNode sf, string text) =>
            sf.Prefix + ApplyCasing(text, sf.Casing) + sf.Suffix;

        /// <summary>Upper/lower-cases the plain-text runs of <paramref name="text"/>, leaving embedded <c>&lt;…&gt;</c> tags verbatim.</summary>
        private static string ApplyCasing(string text, StoryTextCasing casing)
        {
            if (casing == StoryTextCasing.None || text.Length == 0) return text;
            Func<string, string> f = casing == StoryTextCasing.Upper ? s => s.ToUpperInvariant() : s => s.ToLowerInvariant();

            StringBuilder sb   = new();
            int           last = 0;
            foreach (Match m in _EmbeddedTag.Matches(text))
            {
                sb.Append(f(text.Substring(last, m.Index - last)));
                sb.Append(m.Value);
                last = m.Index + m.Length;
            }
            sb.Append(f(text.Substring(last)));
            return sb.ToString();
        }

        /// <summary>The upstream declared variable (a Prev Exit Variable output) identified by <paramref name="fromPoint"/>, or null.</summary>
        private static StoryDeclaredVariable? IncomingVariable(StoryProject project, StoryLogicNode logic, Guid fromPoint)
        {
            if (!logic.AcceptVariables) return null;
            return StorySelectionResolver.IncomingVariables(project, logic).Find(d => d.Id == fromPoint);
        }

        /// <summary>The main-language text of the localization key <paramref name="keyId"/> (empty when unavailable).</summary>
        public static string LocalizedText(LocProject? localization, Guid keyId)
        {
            LocLocalizationKey? key = localization?.Keys.Find(k => k.Id == keyId);
            if (key is null) return "";

            string? main = localization!.Metadata.MainLanguageId;
            if (string.IsNullOrEmpty(main)) return "";
            return key.Translations.Find(t => t.LanguageId == main)?.Text ?? "";
        }

        private static string PreviewValue(StoryVariable v, IReadOnlyDictionary<Guid, string> values) =>
            values.TryGetValue(v.Id, out string? val) ? val : v.PossibleValues.FirstOrDefault() ?? "";

        private static StoryVariable? Variable(StoryProject project, Guid id) =>
            StoryBuiltInVariables.Find(id)
            ?? (id != Guid.Empty && project.Variables.TryGetValue(id, out StoryVariable? v) ? v : null);

        /// <summary>The SmartFormat token name a Get Variable node's Value port supplies under — its override, else the target register's own name (empty when unresolved).</summary>
        private static string GetVariableName(
            StoryProject project, StoryLogicNode logic, StoryGetVariableNode gv,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target)
        {
            if (!string.IsNullOrWhiteSpace(gv.NameOverride)) return gv.NameOverride;
            return StoryLogicFlow.TargetOf(project, logic, gv, values, target)?.Name ?? "";
        }

        /// <summary>The SmartFormat token name a Get Variable node's Slot port supplies under — its own override, else the Value token plus a <c>Slot</c> suffix, so the two ports never collide in one format (empty when unresolved).</summary>
        private static string GetVariableSlotName(
            StoryProject project, StoryLogicNode logic, StoryGetVariableNode gv,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target) =>
            !string.IsNullOrWhiteSpace(gv.SlotNameOverride)
                ? gv.SlotNameOverride.Trim()
                : SlotTokenName(GetVariableName(project, logic, gv, values, target));

        /// <summary>The SmartFormat token a storage variable's slot tag fills — its name plus a <c>Slot</c> suffix (empty when unnamed). Shared by the Get Variable slot port and Register/Set instruction text.</summary>
        public static string SlotTokenName(string variableName) =>
            string.IsNullOrWhiteSpace(variableName) ? "" : variableName.Trim() + "Slot";

        /// <summary>The App-preview value for a Get Variable node — its own preview value, falling back to the target register's when blank.</summary>
        private static string GetVariablePreviewValue(
            StoryProject project, StoryLogicNode logic, StoryGetVariableNode gv,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target) =>
            !string.IsNullOrEmpty(gv.PreviewValue)
                ? gv.PreviewValue
                : StoryLogicFlow.TargetOf(project, logic, gv, values, target)?.PreviewValue ?? "";

        /// <summary>The Gamebook substitution for a Get Variable node's slot port — the referenced slot's styled tag (TA/NA/DA pill).</summary>
        private static string GetVariableSlotTag(
            StoryProject project, StoryLogicNode logic, StoryGetVariableNode gv,
            IReadOnlyDictionary<Guid, string> values, StoryRenderTarget target)
        {
            StoryRegisterVariableNode? reg = StoryLogicFlow.TargetOf(project, logic, gv, values, target);
            if (reg is null) return "";
            return string.IsNullOrWhiteSpace(reg.Name)
                ? PreviewHtmlSanitizer.SlotTag(StorageSlots.Label(reg.Type, reg.SlotIndex))
                : $"<var={reg.Name}>";
        }

        // ── Icon resolution ──────────────────────────────────────────────────────

        private static string? ResolveIconImage(StoryProject project, StoryLogicNode logic, Guid fromPoint, bool paper, int depth)
        {
            if (fromPoint == Guid.Empty || depth > 8) return null;

            if (logic.IconNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryIconNode icon)
                return project.Images.TryGetValue(icon.SelectedImageId, out StoryImage? img) ? img.Data : null;

            if (logic.LightDarkSwitchNodes.Find(n => n.OutPoint.Id == fromPoint) is StoryLightDarkSwitchNode sw)
            {
                Guid input = paper ? sw.LightIn.Id : sw.DarkIn.Id;
                return ResolveIconImage(project, logic, FromPointInto(logic, input), paper, depth + 1);
            }

            return null;
        }

        /// <summary>The output point wired into <paramref name="toPoint"/> (resolved through any logic portal), or empty when nothing is connected.</summary>
        private static Guid FromPointInto(StoryLogicNode logic, Guid toPoint) =>
            logic.ResolvePortalSource(logic.ContentConnections.Find(c => c.ToPoint == toPoint)?.FromPoint ?? Guid.Empty);
    }
}
